-- 22520318 - LUONG VAN DUY --
--I.1: Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính 
-- GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.

CREATE DATABASE QuanLyGiaoVu;
GO
USE QuanLyGiaoVu;
GO

-- TAO BANG (PK columns declared NOT NULL)

CREATE TABLE KHOA (
  MAKHOA   NVARCHAR(4) NOT NULL,
  TENKHOA  NVARCHAR(40),
  NGTLAP   SMALLDATETIME,
  TRGKHOA  NVARCHAR(4)
);

CREATE TABLE MONHOC (
  MAMH   NVARCHAR(10) NOT NULL,
  TENMH  NVARCHAR(40),
  TCLT   TINYINT,
  TCTH   TINYINT,
  MAKHOA NVARCHAR(4)
);

CREATE TABLE DIEUKIEN (
  MAMH        NVARCHAR(10) NOT NULL,
  MAMH_TRUOC  NVARCHAR(10) NOT NULL,
  MAGV        NVARCHAR(4)
);

CREATE TABLE GIAOVIEN (
  MAGV     NVARCHAR(4) NOT NULL,
  HOTEN    NVARCHAR(40),
  HOCVI    NVARCHAR(10),
  HOCHAM   NVARCHAR(10),
  GIOITINH NVARCHAR(3),
  NGSINH   SMALLDATETIME,
  NGVL     SMALLDATETIME,
  HESO     NUMERIC(4,2),
  MUCLUONG MONEY,
  MAKHOA   NVARCHAR(4)
);

CREATE TABLE LOP (
  MALOP   NVARCHAR(3) NOT NULL,
  TENLOP  NVARCHAR(40),
  TRGLOP  NVARCHAR(5),
  SISO    TINYINT,
  MAGVCN  NVARCHAR(4)
);

CREATE TABLE HOCVIEN (
  MAHV    NVARCHAR(5) NOT NULL,
  HO      NVARCHAR(40),
  TEN     NVARCHAR(10),
  NGSINH  SMALLDATETIME,
  GIOITINH NVARCHAR(3),
  NOISINH NVARCHAR(40),
  MALOP   NVARCHAR(3)
);

CREATE TABLE GIANGDAY (
  MALOP   NVARCHAR(3) NOT NULL,
  MAMH    NVARCHAR(10) NOT NULL,
  MAGV    NVARCHAR(4),
  HOCKY   TINYINT,
  NAM     SMALLINT,
  TUNGAY  SMALLDATETIME,
  DENNGAY SMALLDATETIME
);

CREATE TABLE KETQUATHI (
  MAHV   NVARCHAR(5) NOT NULL,
  MAMH   NVARCHAR(10) NOT NULL,
  LANTHI TINYINT NOT NULL,
  NGTHI  SMALLDATETIME,
  DIEM   NUMERIC(4,2),
  KQUA   NVARCHAR(10)
);
GO

-- TAO KHOA CHINH 
ALTER TABLE HOCVIEN 
ADD CONSTRAINT PK_HV PRIMARY KEY (MAHV);

ALTER TABLE LOP 
ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP);

ALTER TABLE KHOA 
ADD CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA);

ALTER TABLE MONHOC 
ADD CONSTRAINT PK_MH PRIMARY KEY (MAMH);

ALTER TABLE DIEUKIEN 
ADD CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC);

ALTER TABLE GIAOVIEN 
ADD CONSTRAINT PK_GV PRIMARY KEY (MAGV);

ALTER TABLE GIANGDAY 
ADD CONSTRAINT PK_GD PRIMARY KEY (MALOP, MAMH);

ALTER TABLE KETQUATHI 
ADD CONSTRAINT PK_KQT PRIMARY KEY (MAHV, MAMH, LANTHI);
GO

-- TAO KHOA NGOAI --
ALTER TABLE HOCVIEN 
ADD CONSTRAINT FK_HV_ML FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE MONHOC 
ADD CONSTRAINT FK_MH_MK FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE GIAOVIEN 
ADD CONSTRAINT FK_GV_MK FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE GIANGDAY 
ADD CONSTRAINT FK_GD_MGV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA_TK FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);
GO

-- THÊM THUỘC TÍNH GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.
ALTER TABLE HOCVIEN
ADD
  GHICHU NVARCHAR(200) NULL,
  DIEMTB NUMERIC(4,2) NULL,
  XEPLOAI NVARCHAR(20) NULL;
GO
 
-- II.1: INSERT 8 BẢNG DỮ LIỆU TIẾNG VIỆT 
-- DU LIEU BANG KHOA
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP) VALUES ('KHMT', N'Khoa học máy tính'			   ,'2005/6/7'  )
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP) VALUES ('HTTT', N'Hệ thống thông tin'		   ,'2005/6/7'  )
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP) VALUES ('CNPM', N'Công nghệ phần mềm'		   ,'2005/6/7'  )
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP) VALUES ('MTT' , N'Mạng máy tính và truyền thông','2005/10/20')
INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP) VALUES ('KTMT', N'Kỹ thuật máy tính'			   ,'2005/12/20')

SELECT * FROM [dbo].[KHOA]

--DU LIEU BANG MON HOC
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('THDC'    ,N'Tin học đại cương',			 4, 1, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('CTRR'    ,N'Cấu trúc rời rạc',			 3, 0, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('CSDL'    ,N'Cơ sở dữ liệu',			 3, 1, 'HTTT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('CTDLGT'  ,N'Cấu trúc dữ liệu và giải thuật',	 3, 1, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('PTTKTT'  ,N'Phân tích thiết kế thuật toán',	 3, 0, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('DHMT'    ,N'Đồ họa máy tính',			 3, 1, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('KTMT'    ,N'Kiến trúc máy tính',			 3, 0, 'KTMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('TKCSDL'  ,N'Thiết kế cơ sở dữ liệu',		 4, 1, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('PTTKHTTT',N'Phân tích thiết kế hệ thống thông tin', 4, 1, 'KHMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('HDH'     ,N'Hệ điều hành',				 4, 1, 'KTMT')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('NMCNPM'  ,N'Nhập môn công nghệ phần mềm',		 3, 0, 'CNPM')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('LTCFW'   ,N'Lập trình C for win',			 3, 0, 'CNPM')
INSERT INTO MONHOC(MAMH, TENMH, TCLT, TCTH, MAKHOA) VALUES ('LTHDT'   ,N'Lập trình hướng đối tượng',		 3, 1, 'CNPM')

SELECT * FROM MONHOC

--DU LIEU BANG DIEU KIEN 
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('CSDL'    , 'CTRR'  )
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('CSDL'    , 'CTDLGT')
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('CTDLGT'  , 'THDC'  )
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('PTTKTT'  , 'THDC'  )
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('PTTKTT'  , 'CTDLGT')
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('DHMT'    , 'THDC'  )
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('LTHDT'   , 'THDC'  )
INSERT INTO DIEUKIEN(MAMH, MAMH_TRUOC) VALUES ('PTTKHTTT', 'CSDL'  )

SELECT * FROM DIEUKIEN
 
 -- DU LIEU BANG GIAO VIEN 
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV01', N'Hồ Thanh Sơn'	,'PTS', 'GS'  , N'Nam', '1950/5/2'  , '2004/1/11', 5.00, 2250000, 'KHMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV02', N'Trần Tâm Thanh'	,'TS' , 'PGS' , N'Nam', '1965/12/17', '2004/4/20', 4.50, 2025000, 'HTTT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV03', N'Đỗ Nghiêm Phụng'	,'TS' , 'GS'  , N'Nữ' , '1950/8/1'  , '2004/9/23', 4.00, 1800000, 'CNPM')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV04', N'Trần Nam Sơn'	,'TS' , 'PGS' , N'Nam', '1961/2/22' , '2005/1/12', 4.50, 2025000, 'KTMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV05', N'Mai Thanh Danh'	,'ThS', 'GV'  , N'Nam', '1958/3/12' , '2005/1/12', 3.00, 1350000, 'HTTT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV06', N'Trần Đoàn Hùng'	,'TS' , 'GV'  , N'Nam', '1953/3/11' , '2005/1/12', 4.50, 2025000, 'KHMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV07', N'Nguyễn Minh Tiến'    ,'ThS', 'GV'  , N'Nam', '1971/11/23', '2005/3/1' , 4.00, 1800000, 'KHMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV08', N'Lê Thị Trân'		,'KS' , 'Null', N'Nữ' , '1974/3/26' , '2005/3/1' , 1.69, 760500 , 'KHMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV09', N'Nguyễn Tô Lan'	,'ThS', 'GV'  , N'Nữ' , '1966/12/31', '2005/3/1' , 4.00, 1800000, 'HTTT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV10', N'Lê Trần Anh Loan'	,'KS' , 'Null', N'Nữ' , '1972/7/17' , '2005/3/1' , 1.86, 8370000, 'CNPM')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV11', N'Hồ Thanh Tùng'	,'CN' , 'GV'  , N'Nam', '1980/1/12' , '2005/5/15', 2.67, 1201500, 'MTT' )
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV12', N'Trần Vân Anh'	,'CN' , 'Null', N'Nữ' , '1981/3/29' , '2005/5/15', 1.69, 760500 , 'CNPM')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV13', N'Nguyễn Linh Đan'	,'CN' , 'Null', N'Nữ' , '1980/5/23' , '2005/5/15', 1.69, 760500 , 'KTMT')
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV14', N'Trương Minh Châu'	,'ThS', 'GV'  , N'Nữ' , '1976/11/30', '2005/5/15', 3.00, 1350000, 'MTT' )
INSERT INTO GIAOVIEN(MAGV, HOTEN, HOCVI, HOCHAM, GIOITINH, NGSINH, NGVL, HESO, MUCLUONG, MAKHOA) VALUES ('GV15', N'Lê Hà Thanh'		,'ThS', 'GV'  , N'Nam', '1978/5/4'  , '2005/5/15', 3.00, 1350000, 'KHMT')

SELECT * FROM GIAOVIEN 

--DU LIEU BANG LOP 
INSERT INTO LOP(MALOP, TENLOP, SISO, MAGVCN) VALUES ('K11',N'Lớp 1 khóa 1',11,'GV07')
INSERT INTO LOP(MALOP, TENLOP, SISO, MAGVCN) VALUES ('K12',N'Lớp 2 khóa 1',12,'GV09')
INSERT INTO LOP(MALOP, TENLOP, SISO, MAGVCN) VALUES ('K13',N'Lớp 3 khóa 1',12,'GV14')

SELECT * FROM LOP

--DU LIEU BANG HOCVIEN 
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1101',N'Nguyễn Văn'	,N'A'	  ,'1986/1/27', N'Nam' ,N'TpHCM'     ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1102',N'Trần Ngọc'	,N'Hân'   ,'1986/3/14', N'Nữ'  ,N'Kiên Giang','K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1103',N'Hà Duy'		,N'Lập'   ,'1986/4/18', N'Nam' ,N'Nghệ An'   ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1104',N'Trần Ngọc' 	,N'Linh'  ,'1986/3/30', N'Nữ'  ,N'Tây Ninh'  ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1105',N'Trần Minh'	,N'Long'  ,'1986/2/27', N'Nam' ,N'TpHCM'     ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1106',N'Lệ Nhật'		,N'Minh'  ,'1986/1/24', N'Nam' ,N'TpHCM'     ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1107',N'Nguyễn Như'	,N'Nhựt'  ,'1986/1/27', N'Nam' ,N'Hà Nội'    ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1108',N'Nguyễn Mạnh'	,N'Tâm'   ,'1986/2/27', N'Nam' ,N'Kiên Giang','K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1109',N'Phan Thị Thanh' 	,N'Tâm'   ,'1986/1/27', N'Nữ'  ,N'Vĩnh Long' ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1110',N'Lê Hoài'		,N'Thương','1986/2/5' , N'Nữ'  ,N'Cần Thơ'   ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1111',N'Lê Hà'		,N'Vinh'  ,'1986/2/25', N'Nam' ,N'Vĩnh Long' ,'K11')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1201',N'Nguyễn Văn'      ,N'B'	  ,'1986/2/11', N'Nam' ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1202',N'Nguyễn Thị Kim'  ,N'Duyên' ,'1986/1/18', N'Nữ'  ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1203',N'Trần Thị Kim'    ,N'Duyên' ,'1986/9/17', N'Nữ'  ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1204',N'Trương Mỹ'	,N'Hạnh'  ,'1986/5/19', N'Nữ'  ,N'Đồng Nai'  ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1205',N'Nguyễn Thành'    ,N'Nam'   ,'1986/4/17', N'Nam' ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1206',N'Nguyễn Thị Trúc' ,N'Thanh' ,'1986/3/4' , N'Nữ'  ,N'Kiên Giang','K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1207',N'Trần Thị Bích'   ,N'Thủy'  ,'1986/2/8' , N'Nữ'  ,N'Nghệ An'   ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1208',N'Huỳnh Thị Kim'   ,N'Triều' ,'1986/4/8' , N'Nữ'  ,N'Tây Ninh'  ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1209',N'Phạm Thanh'	,N'Triều' ,'1986/2/23', N'Nam' ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1210',N'Ngô Thanh'	,N'Tuấn'  ,'1986/2/14', N'Nam' ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1211',N'Đỗ Thị'		,N'Xuân'  ,'1986/3/9' , N'Nữ'  ,N'Hà Nội'    ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1212',N'Lê Thị Phi'	,N'Yến'   ,'1986/3/12', N'Nữ'  ,N'TpHCM'     ,'K12')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1301',N'Nguyễn Thị Kim'  ,N'Cúc'   ,'1986/6/9' , N'Nữ'  ,N'Kiên Giang','K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1302',N'Trương Thị Mỹ'   ,N'Hiền'  ,'1986/3/18', N'Nữ'  ,N'Nghệ An'   ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1303',N'Lê Đức'          ,N'Hiền'  ,'1986/3/21', N'Nam' ,N'Tây Ninh'  ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1304',N'Lê Quang'	,N'Hiền'  ,'1986/4/18', N'Nam' ,N'TpHCM'     ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1305',N'Lê Thị'          ,N'Hương' ,'1986/3/27', N'Nữ'  ,N'TpHCM'     ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1306',N'Nguyễn Thái'	,N'Hữu'   ,'1986/3/30', N'Nam' ,N'Hà Nội'    ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1307',N'Trần Minh'	,N'Mẫn'   ,'1986/5/28', N'Nam' ,N'TpHCM'     ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1308',N'Nguyễn Hiếu'	,N'Nghĩa' ,'1986/4/8' , N'Nam' ,N'Kiên Giang','K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1309',N'Nguyễn Trung'    ,N'Nghĩa' ,'1987/1/18', N'Nam' ,N'Nghệ An'   ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1310',N'Trần Thị Hồng'   ,N'Thắm'  ,'1986/4/22', N'Nữ'  ,N'Tây Ninh'  ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1311',N'Trần Minh'       ,N'Thức'  ,'1986/4/4' , N'Nam' ,N'TpHCM'     ,'K13')
INSERT INTO HOCVIEN(MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES ('K1312',N'Nguyễn Thị Kim'  ,N'Yến'   ,'1986/9/7' , N'Nữ'  ,N'TpHCM'     ,'K13')

SELECT * FROM HOCVIEN 

--DU LIEU BANG GIANGDAY 
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','THDC'  ,'GV07',1,2006,'2006/1/2' ,'2006/5/12' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K12','THDC'  ,'GV06',1,2006,'2006/1/2' ,'2006/5/12' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K13','THDC'  ,'GV15',1,2006,'2006/1/2' ,'2006/5/12' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','CTRR'  ,'GV02',1,2006,'2006/1/9' ,'2006/5/17' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K12','CTRR'  ,'GV02',1,2006,'2006/1/9' ,'2006/5/17' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K13','CTRR'  ,'GV08',1,2006,'2006/1/9' ,'2006/5/17' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','CSDL'  ,'GV05',1,2006,'2006/6/1' ,'2006/7/15' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K12','CSDL'  ,'GV09',2,2006,'2006/6/1' ,'2006/7/15' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K13','CTDLGT','GV15',2,2006,'2006/6/1' ,'2006/7/15' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K13','CSDL'  ,'GV05',3,2006,'2006/8/1' ,'2006/12/15')
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K13','DHMT'  ,'GV07',3,2006,'2006/8/1' ,'2006/12/15')
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','CTDLGT','GV15',3,2006,'2006/8/1' ,'2006/12/15')
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K12','CTDLGT','GV15',3,2006,'2006/8/1' ,'2006/12/15')
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','HDH'   ,'GV04',1,2007,'2007/1/2' ,'2007/2/18' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K12','HDH'   ,'GV04',1,2007,'2007/1/2' ,'2007/3/20' )
INSERT INTO GIANGDAY(MALOP, MAMH, MAGV, HOCKY, NAM, TUNGAY, DENNGAY) VALUES ('K11','DHMT'  ,'GV07',1,2007,'2007/2/18','2007/3/20' )

SELECT * FROM GIANGDAY 

--DU LIEU BANG KETQUATHI 
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1101','CSDL'  , 1,'2006/7/20' , 10.00,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1101','CTDLGT', 1,'2006/12/28', 9.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1101','THDC'  , 1,'2006/5/20' , 9.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1101','CTRR'  , 1,'2006/5/13' , 9.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CSDL'  , 1,'2006/7/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CSDL'  , 2,'2006/7/27' , 4.25 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CSDL'  , 3,'2006/8/10' , 4.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CTDLGT', 1,'2006/12/28', 4.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CTDLGT', 2,'2007/1/5'  , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CTDLGT', 3,'2007/1/15' , 6.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','THDC'  , 1,'2006/5/20' , 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1102','CTRR'  , 1,'2006/5/13' , 7.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1103','CSDL'  , 1,'2006/7/20' , 3.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1103','CSDL'  , 2,'2006/7/27' , 8.25 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1103','CTDLGT', 1,'2006/12/28', 7.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1103','THDC'  , 1,'2006/5/20' , 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1103','CTRR'  , 1,'2006/5/13' , 6.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','CSDL'  , 1,'2006/7/20' , 3.75 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','CTDLGT', 1,'2006/12/28', 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','THDC'  , 1,'2006/5/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','CTRR'  , 1,'2006/5/13' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','CTRR'  , 2,'2006/5/20' , 3.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1104','CTRR'  , 3,'2006/6/30' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1201','CSDL'  , 1,'2006/7/20' , 6.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1201','CTDLGT', 1,'2006/12/28', 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1201','THDC'  , 1,'2006/5/20' , 8.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1201','CTRR'  , 1,'2006/5/13' , 9.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CSDL'  , 1,'2006/7/20' , 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CTDLGT', 1,'2006/12/28', 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CTDLGT', 2,'2007/1/5'  , 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','THDC'  , 1,'2006/5/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','THDC'  , 2,'2006/5/27' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CTRR'  , 1,'2006/5/13' , 3.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CTRR'  , 2,'2006/5/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1202','CTRR'  , 3,'2006/6/30' , 6.25 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1203','CSDL'  , 1,'2006/7/20' , 9.25 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1203','CTDLGT', 1,'2006/12/28', 9.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1203','THDC'  , 1,'2006/5/20' , 10.00,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1203','CTRR'  , 1,'2006/5/13' , 10.00,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1204','CSDL'  , 1,'2006/7/20' , 8.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1204','CTDLGT', 1,'2006/12/28', 6.75 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1204','THDC'  , 1,'2006/5/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1204','CTRR'  , 1,'2006/5/13' , 6.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1301','CSDL'  , 1,'2006/7/20' , 4.25 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1301','CTDLGT', 1,'2006/12/28', 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1301','THDC'  , 1,'2006/5/20' , 7.75 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1301','CTRR'  , 1,'2006/5/13' , 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1302','CSDL'  , 1,'2006/12/20', 6.75 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1302','CTDLGT', 1,'2006/7/25' , 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1302','THDC'  , 1,'2006/5/20' , 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1302','CTRR'  , 1,'2006/5/13' , 8.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CSDL'  , 1,'2006/7/20' , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CTDLGT', 1,'2006/7/25' , 4.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CTDLGT', 2,'2007/8/7'  , 4.00 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CTDLGT', 3,'2006/8/15' , 4.25 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','THDC'  , 1,'2006/5/20' , 4.50 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CTRR'  , 1,'2006/5/13' , 3.25 ,N'Không Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1303','CTRR'  , 2,'2006/5/20' , 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1304','CSDL'  , 1,'2006/12/20', 7.75 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1304','CTDLGT', 1,'2006/7/25' , 9.75 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1304','THDC'  , 1,'2006/5/20' , 5.50 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1304','CTRR'  , 1,'2006/5/13' , 5.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1305','CSDL'  , 1,'2006/12/20', 9.25 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1305','CTDLGT', 1,'2006/7/25' , 10.00,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1305','THDC'  , 1,'2006/5/20' , 8.00 ,N'Đạt')
INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA) VALUES ('K1305','CTRR'  , 1,'2006/5/13' , 10.00,N'Đạt')

SELECT * FROM KETQUATHI 